### PR TITLE
Add proper license to our project

### PR DESCRIPTION
**Pull request by MrParris**
In a ideal world this license is inserted as a header in all of our code files. For now it is inserted only in our root repository.

### CODE REVIEW

**Comment by edouard1195** [comment]
I thought the licence was apache and not MIT, might want to change that. Git has an option to set the license (Insight>Community), might be a good idea to put it there. Apache has a "short licence" that we can add at the start of files, might be a good idea to add that too.

**Review by edouard1195 — CHANGES_REQUESTED** [review]
Not the right licence ? Look at my other comment.
https://www.apache.org/licenses/LICENSE-2.0

**Comment by MrParris** [comment]
Yes it's planned for Apache, I didn't put the time in it yet

**Comment by MrParris** [comment]
Here now done

**Pull request merged**
