### PR TITLE
Sec 260 teleop node

### PR DESCRIPTION
**Pull request by edouard1195**

### CODE REVIEW

**Comment by MoronixProduct3** [comment]
Why is the `video_device_label` not a parameter anymore?

It's been commented out of launch files and removed from some code snippets on the electron side.

**Comment by edouard1195** [comment]
Because we have 2 virtual devices that the electron application needs to get and if you look here (https://answers.ros.org/question/194592/how-to-read-a-vectorstrings-parameter-from-command-line/), putting the names as an array of string value in a param cannot be done, we would need to do more like parsing a string with predefined delimiters or create a script to add the array directly on the server which seems more complicated than needed. An other solutions could be to have 2 param defining each name, but that's the same as having an array in the code that contains the names and it is also simpler to iterate on the array than the parameters. It's also simpler for debugging to have an array than parameters in my opinion. If we want them to not be hardcoded, we can use a config file or something else, but for now I think this is fine.

**Comment by MoronixProduct3** [comment]
Makes sense, you can still pass two string parameters, one for each video stream you need to connect.
And if for some reason the chose implementation is to not pass them as parameters, they should be completely removed and not left as commented lines in the launch files and code.

**Comment by edouard1195** [comment]
As i said yesterday (just to keep track here), I agree that there should be no dead code. I believe everything on _master_ should be as clean and "perfect" as possible, but we can allow ourselves some loose on dev for experimentation and so not necessarily keep everything perfect if we aren't sure of some parts. Since we currently have a task in waiting to clean the code of the electron app and refactor it, I believe ti request can be merge on dev, but the cleaning task need to be done before the merge with master. The moment this is push on dev, the task for cleaning will start (branch) and everything on the electron app will be looked into for that. 

As for the array part, I think it's ok to keep it like as is for now, I don't really see why we develop something for it right now when we specifically said that this sprint would have no development, only cleaning and tweaking to prepare for a master merge.

If you still have issues with the branch, please just close it so I know what to do with it, since a lot of what i have to do during this sprint depend on this being merge. Thank you!

**Review by MoronixProduct3 — APPROVED** [review]
Merging towards dev.

**Pull request merged**
